import { v4 } from "uuid";
import { ProductTypes } from "../components/ProductCard/types";
import pizzaImg from "../assets/pizzas/custom.jpg";

export const FakeData: ProductTypes[] = [
  {
    currency: "ден",
    description: "Ова е најдобрата пица во градот",
    priceFrom: 300,
    priceTo: 500,
    title: "Мичовата пица",
    key: v4(),
    image: pizzaImg,
  },
  {
    currency: "ден",
    description: "Ова е најдобрата пица во градот",
    priceFrom: 300,
    priceTo: 500,
    title: "Мичовата пица",
    key: v4(),
    image: pizzaImg,
  },
  {
    currency: "ден",
    description: "Ова е најдобрата пица во градот",
    priceFrom: 300,
    priceTo: 500,
    title: "Мичовата пица",
    key: v4(),
    image: pizzaImg,
  },
  {
    currency: "ден",
    description: "Ова е најдобрата пица во градот",
    priceFrom: 300,
    priceTo: 500,
    title: "Мичовата пица",
    key: v4(),
    image: pizzaImg,
  },
  {
    currency: "ден",
    description: "Ова е најдобрата пица во градот",
    priceFrom: 300,
    priceTo: 500,
    title: "Мичовата пица",
    key: v4(),
    image: pizzaImg,
  },
  {
    currency: "ден",
    description: "Ова е најдобрата пица во градот",
    priceFrom: 300,
    priceTo: 500,
    title: "Мичовата пица",
    key: v4(),
    image: pizzaImg,
  },
  {
    currency: "ден",
    description: "Ова е најдобрата пица во градот",
    priceFrom: 300,
    priceTo: 500,
    title: "Мичовата пица",
    key: v4(),
    image: pizzaImg,
  },
  {
    currency: "ден",
    description: "Ова е најдобрата пица во градот",
    priceFrom: 300,
    priceTo: 500,
    title: "Мичовата пица",
    key: v4(),
    image: pizzaImg,
  },
  {
    currency: "ден",
    description: "Ова е најдобрата пица во градот",
    priceFrom: 300,
    priceTo: 500,
    title: "Мичовата пица",
    key: v4(),
    image: pizzaImg,
  },
  {
    currency: "ден",
    description: "Ова е најдобрата пица во градот",
    priceFrom: 300,
    priceTo: 500,
    title: "Мичовата пица",
    key: v4(),
    image: pizzaImg,
  },
];
