import Head from "next/head";
import Main from "../components/Section/Main";
import PizzaSection from "../components/Section/PizzaSection";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Пицерија Spalato</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <PizzaSection />
    </div>
  );
}
