import Head from "next/head";
import Past from "../components/PastSection/Past";
import ProductSection from "../components/ProductSection/ProductSection";
import Main from "../components/Section/Main";
import { FakeData } from "../assets/mockData";
import Footer from "../components/Footer/Footer";
import { PrismaClient } from "@prisma/client";
import { ProductTypes } from "../components/ProductCard/types";
import Scrollbars from "react-custom-scrollbars-2";

export async function getStaticProps() {
  const prisma = new PrismaClient();
  const products = await prisma.product.findMany();

  return {
    props: { products },
  };
}

export default function Home(products: ProductTypes) {
  console.log(products);
  return (
    <div style={{ height: "100vh" }}>
      <Scrollbars universal={true} autoHide>
        <Head>
          <title>Пицерија Spalato</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Main />
        <ProductSection title="Пица" data={FakeData} />
        <Past />
        <ProductSection title="Сендвичи" data={FakeData} />
        <ProductSection title="Пијалоци" data={FakeData} />
        <Footer />
      </Scrollbars>
    </div>
  );
}
